# **(MONTE-CARLO 'FERMI ESTIMATION' APPROACHES)** {-#fermi}


'BOTEC': Back of the envelope calculations are central to RP's work

'Fermi estimation' is essentially a more formal approach to this, carefully defining and explaining each element of the 'model' equation

When we explicitly define (and justify) a probability distribution over each variable in the model, and compute (often through simulation) the overall uncertainty of the outputs (predictions, estimates, etc), we call this "Monte Carlo Fermi Estimation" (at least David Reinstein thinks this is what it's called).


David Reinstein and Sam Nolan explain this approach, advocating its use in GiveWell models and beyond, lay out some building blocks,

... and embed some tools and work-in-progress on this [HERE](https://effective-giving-marketing.gitbook.io/innovations-in-givewell-esque-ceas/),  also embedded below.


```{r wppage}

knitr::include_url("https://effective-giving-marketing.gitbook.io/innovations-in-givewell-esque-ceas/")

```

::: {.alert .alert-secondary}

DR: We may want to look for ways to explicitly incorporate and integrate these approaches into our data analysis work in R, etc.

w:::
