
# EA Survey: Presentation, methodology

*Note: this has been moved from the ea-data repo, and is being expanded here*

## Organisation, collophon, formatting

### How this is built, how it works, how it relates to EA Forum posts

### Markdown formatting, conversion, etc.

We need to convert this Rmd/html 'bookdown' output into a format acceptable for the EA Forum (however, we can also separately link and host this bookdown, or parts of it, as we do [HERE](https://rethinkpriorities.github.io/ea_data_public/outline-disc.html).

Typically, RP has made these posts first in Google Docs for feedback and then there is some sort of sprocedure to get it into EA forum markdown syntax from there. For some previous posts, we pasted from the Rstudio visual mode pastes into Google docs for narrative, and figures/tables could be manually pasted. But we want to avoid having to do that!

We hope this can be done through simple script Pandoc plus a simple adjustment script (in Python or Vim etc).

\

*Some formatting adjustments will be necessary, however:*

-   EA Forum doesn't have margin notes or folding boxes. Margin notes should be made into footnotes. (Or notes in parentheses if they need to be prominent). Folded boxes should probably be retained in the (linked) hosted bookdown only.

NOTE: remaining content moved to [methodology](https://github.com/rethinkpriorities/methodology-statistics-design) repo

## Coding and organisational issues

## Content and methods

### Visualisations

See also Gdoc: [visualisation discussions](https://docs.google.com/document/d/1U_k_sIPDQmkKgatgXStDqrwi-g3vPGgftYbN8AEDPhs/edit#)

#### Ideal coding practice for visualisations

Use `ggplot` always unless you've a strong reason to do otherwise. Always save the plot as an object in the environment as well as printing it where it belongs.

Ideally, we will come up with a set of functions and default options for the key sets of plots we use and like.

Define and reuse lists of labels (or use inherent labeling options where these exist, to exploit existing variable and value labels.)

Otherwise define sets of common options for plots in one place, and repeated ggplot elements together as a list:

-   to avoid repetition and clutter

-   to allow easy 'global' adjustment

#### Labeling

Use readable but concise labels. "Amount donated" is OK, "GWWC" is OK because we assume people know what GWWC is from context.

`amt_don` is not OK.

#### Relative shares of a total; e.g. 'shares of EA population by referrer', or 'donation totals by country'

**Treemaps**

```{block2,  type='note'}
NOTE: The below will not run without data, but we cannot make data 'public' here ... we need to make some choices ... or maybe use simulated data in this discussion
```

```{r}

geom_treemap_opts <- list(geom_treemap(alpha = 0.7),
  geom_treemap_text(fontface = "italic", colour = "white", place = "centre",
                    grow = TRUE, min.size = 1 ),
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5))
  )

(
  don_share_by_size <- eas_20 %>% select(donation_2019_c, donation_2019_c_split) %>%
  group_by(donation_2019_c_split) %>%
  summarise(total_don = sum(donation_2019_c, na.rm=TRUE)) %>%
  mutate(don_share = round(total_don/sum(total_don)*100)) %>%
  filter(!is.na(donation_2019_c_split)) %>%
  ggplot(aes(area = total_don, fill= donation_2019_c_split,
             # Include percentage of total donation
             label = paste(donation_2019_c_split, paste0(don_share, "%"), sep = "\n"))) +
    geom_treemap_opts +
  ggtitle("Share of total 2019 reported donation amount, by donation size")
)
```

A good alternative to the treemap ... conveying both absolute amounts and rates in the same graph?

#### Likert scale (individual items) and relative responses to these

#### Dealing with scales and large differences in magnitudes

If axes are cut and don't go to zero, mention this prominently in the plot.

But what if we have a few values that are way above others, and 'mess up the scale'?

Sometimes a logarithmic scale is helpful, but that can also lead to confusion. Otherwise...

-   "any CI's or other things that go outside of the limits should just be extended to the edge and not dropped)"

    -   doable with scale_y\_continuous( oob = scales::squish) +

        scale_x\_continuous( oob = scales::squish)`` or  `coord_cartesian` ``

-   or otherwise allow a clear 'break' in the axis?

-   Not possible to break the axis ggplot <https://stackoverflow.com/questions/7194688/using-ggplot2-can-i-insert-a-break-in-the-axis>

-   @Oska -- what about 'extending to the edge'?

Remove outliers as a last resort; prominently mention this where doing so.

#### Means of continuous variables: differences across groups

#### Visualizing (regression) model coefficients and confidence intervals

Testing a reference @wickham2010

### Statistical tests (make a new section)s

### 'Models'

Contrast:

-   Descriptive (and perhaps causally suggestive), aka 'dimension reduction'

-   Predictive

-   Causal

See discussion in Engagement section [here](#modeling_disc_eng)

### Model coding and implementation practice

**Define lists of variables (features) up front** (see, e.g., in engagement post ['Choosing features...'](engage_features))

-   outcomes,
-   'predictors' or associated variables of interest, (define broad and narrow sets, consider endogeneity of various forms, e.g., 'colliders', consider 'clean model without leacks' for specific prediction exercises)
-   'control variables' (not of direct interest but included because they are believed to improve interpretation of variables of interest; note this can be problematic), 'robust controls' for more flexible control

E.g.,

    cat_out <- "engagement" #categorical outcome
    key_demog <- c("age_approx_d2sd", "gender_cat", "student_cat", "race_cat", geog)
    controls <- c("years_involved_d2sd")

**Missing values:** Impute or code as separate 'NA' category

**Normalize continuous variables** (de-mean, divide continuous variables by 2sd if comparing coefficients to binary variables)

**Categorical/discrete variables**:
