{
  "hash": "57fac808e0f7a42435953591ddb80fc3",
  "result": {
    "markdown": "# Inference/equivalence testing w. binomial outcomes\n\n\n\n\n::: {.alert .alert-secondary}\n \n\nThis work has been moved from the EA market testing repo, with 'identifying' content redacted\n\n:::\n\n\nThe context for this trial is discussed [here (private)](https://app.gitbook.com/o/-MfFk4CTSGwVOPkwnRgx/s/-Mf8cHxdwePMZXRTKnEE/c/0qFJ2AUh7cZzynp3zRjk/contexts-and-environments-for-testing/one-for-the-world/pre-giving-tuesday-email-split-test) and will be publicly shared [here]() when we gain permission.\n\n## Input from Gsheet (WIP)\n\n::: {.cell}\n\n```{.r .cell-code}\n#library(googlesheets4)\n#read_sheet(\"XXX\")\n#Need authorization here; how to do it? Note -- we need those cells to be anonymized \n```\n:::\n\n\n\nNote: subject lines were different ... the impact email got more opens\n\n'Giving Season contributions - website' for donations ... because CtA is a donation button on the website\n\n## Randomization inference approach \n\n## How likely is the 'imbalance of unique emails' due to chance?\n\nWe've 1345 unique emails in the dataset for ‘control’ treatment 1 and 1190 unique emails for treatment 2, if I did the quick calculations correctly. (Todo-- integrate the data here.)\n\nWe know some emails are repeated. To analyze this correctly I should bring in the actual distribution of 'number of times an email is in the data' and simulate assignment. (Or maybe this is a 'Poisson' thing?)\n\nAs a (perhaps incorrect) first pass I could consider 'legitimate unique email shows up in the treatment group' as a random binomial event. (I guess the event is something like 'email is  (not) duplicated?) Then we can do the standard binomial (Chi-sq) and Fisher's exact tests.\n\n::: {.cell}\n\n```{.r .cell-code}\nn1 <- 1345\nn2 <- 1190\n\n(\n  binom_emails <- prop.test(n1, n1+n2, correct=FALSE)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  n1 out of n1 + n2, null probability 0.5\nX-squared = 9.4773, df = 1, p-value = 0.00208\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.5111129 0.5499385\nsample estimates:\n       p \n0.530572 \n```\n:::\n\n```{.r .cell-code}\n(\n  fisher_emails <- fisher.test(matrix(c(n1, n2, n2, n1), ncol=2))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  matrix(c(n1, n2, n2, n1), ncol = 2)\np-value = 1.512e-05\nalternative hypothesis: true odds ratio is not equal to 1\n95 percent confidence interval:\n 1.142247 1.428639\nsample estimates:\nodds ratio \n  1.277394 \n```\n:::\n:::\n\nIf the above tests are reasonable, this imbalance is very unlikely to occur by chance.\n\n\nNote: if we think this is opens, this is a demonstration that one email is opened more. \n\n\n\n\n## How likely are  'proportions this similar' under different size 'true effect sizes'?^[ I think this is relates to a 'power calculation', but reporting $1-power$.\n]\n\n\nIn the next section I started an off-the-cuff simulation approach, in folded code. But I believe that the *analytical* form [here](https://math.stackexchange.com/questions/562119/difference-of-two-binomial-random-variables) with code and a simulation [here](https://gist.github.com/coppeliaMLA/9681819) should be applicable.\n\n###  Difference between two binomial random variables.\n\n**Reprinting and discussing from [Stackexchange post](https://math.stackexchange.com/questions/562119/difference-of-two-binomial-random-variables)**\n\n\"derive the distribution of the difference between two binomial random variables.\"\n\n> I can give you an answer for the pmf of X-Y. From there \\|X - Y\\| is straightforward.\n\n> So we start with\n>\n> $X \\sim Bin(n_1, p_1)$\n>\n> $Y \\sim Bin(n_2, p_2)$\n>\n> We are looking for the probability mass function of $Z=X-Y$\n\n*Note:* in our case we (arguably) care about the difference in 'proportion of incidences', but as we also have similar sample sizes ($n_1 \\approx n_2$) this is basically a normalization\n\n> First note that the min and max of the support of Z must be $(-n_2, n_1)$ since that covers the most extreme cases ($X=0$ and $Y=n_2$) and ($X=n_1$ and $Y=0$).\n>\n> Then we need a modification of the binomial pmf so that it can cope with values outside of its support.\n>\n> $m(k, n, p) = \\binom {n} {k} p^k (1-p)^{n-k}$ when $k \\leq n$ and 0 otherwise.\n\nNote that this \"modified binomial\" *is* what the `statistics::dbinom` function in R returns.\n\n> Then we need to define two cases\n>\n> 1.  $Z \\geq 0$\n> 2.  $Z \\lt 0$\n>\n> In the first case\n>\n> $p(z) = \\sum_{i=0}^{n_1} m(i+z, n_1, p_1) m(i, n_2, p_2)$\n>\n> since this covers all the ways in which X-Y could equal z. \\\n\nBecause $(i+z) - i = z$, of course ... 'sum up' the probability of each of these 'co-occurances'\n\n> For example when z=1 this is reached when X=1 and Y=0 and X=2 and Y=1 and X=3 and Y=4 and so on. It also deals with cases that could not happen because of the values of $n_1$ and $n_2$. For example if $n_2 = 4$ then we cannot get Z=1 as a combination of X=4 and Y=5. In this case thanks to our modified binomial pmf the probablity is zero.\n>\n> For the second case we just reverse the roles. For example if z=-1 then this is reached when X=0 and Y=1, X=1 and Y=2 etc.\n>\n> $p(z) = \\sum_{i=0}^{n_2} m(i, n_1, p_1) m(i+z, n_2, p_2)$\n>\n> Put them together and that's your pmf.\n\n$f(z)=$\n\n```{=tex}\n\\begin{cases}\n    \\sum_{i=0}^{n_1} m(i+z, n_1, p_1) m(i, n_2, p_2),& \\text{if } z\\geq 0\\\\\n    \\sum_{i=0}^{n_2} m(i, n_1, p_1) m(i+z, n_2, p_2),              & \\text{otherwise}\n\\end{cases}\n```\n> Here's the function in R and a simulation to check it's right (and it does work.) <https://gist.github.com/ragscripts/9681819>\n\nLet me try to apply it...\n\nDefining their code for this function:\n::: {.cell}\n\n```{.r .cell-code}\nmodBin <-dbinom #DR: I just do this renaming here for consistency with the rest ... but the modBin they defined was redundant\n\ndiffBin<-function(z, n1, p1, n2, p2){\n\n  prob <- 0\n\n  if (z>=0){\n    for (i in 1:n1){\n      prob <- prob + modBin(i+z, n1, p1) * modBin(i, n2, p2)\n    }\n\n  }\n  else\n  {\n    for (i in 1:n2){\n      prob<-prob+modBin(i+z, n1, p1)*modBin(i, n2, p2)\n    }\n  }\n  return(prob)\n}\n```\n:::\n\n### Applying this to present data\n\nRather than using their example, I'll dive right in to the present case.\n\nMy notes on the outcomes as of 15 Dec 2021\n\n::: {.callout-note collapse='true'}\n Treatment 1 - Impact and\nTreatment 2 - Emotion Story tabs\n\nTreatment 1: We record\n- 8 unique emails donating, 26 donations in total,\n- worth 5200 USD in total\n- 1345 unique emails listed as getting  ‘control’ treatment 1\n\nTreatment 2:\n-  6 unique emails, 28 donations so far\n—  worth 7500 USD in total.\n- 1190 unique emails listed for treatment 2\n\nIf I believe my ‘unique emails count’, that implies\nan 0.59% ‘conversion’ rate for T1 - Control\na 0.50% conversion rate for T2 - Emotion/Story\n \n \n:::\n\nPutting the observations into defined objects (later: do from data)\n\n::: {.cell}\n\n```{.r .cell-code}\nn1 <- 1345\nn2 <- 1190\nd1 <- 8\nd2 <- 6\nz <- d1-d2\n```\n:::\n\nComputation for a few 'ad-hoc cases' (later explore the space with vectors of values)\n\n1. Suppose truly equal incidence, at the mean level\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- (d1+d2)/(n1+n2)\n\np2 <- p1\n\n(\n  db_0 <- diffBin(z, n1, p1, n2, p2)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1024599\n```\n:::\n:::\n\nThis implies there is a 10.2% chance of getting this *exact* difference of +2 incidences between the treatments (in one direction), if the true incidence rates were equal.\n\nLet's plot this for a range of 'incidence rate differences' in this region. (Sorry, using the traditional plot, ggplot is better).\n\n::: {.cell}\n\n```{.r .cell-code}\ns <- seq(-10*z, 10*z)\np<-sapply(s, function(z) diffBin(z, n1, p1, n2, p2))\nplot(s,p)\n```\n\n::: {.cell-output-display}\n![](binary_trial_computations_redacted_ed_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\nWe see a large likelihood of values in the range of the +2 difference observed, and a low likelihood of a difference of 10 or more in either direction.\n\n### Adaptation: 'of this magnitude or smaller'\n\n::: {.cell}\n\n```{.r .cell-code}\nltmag_diffBin <- function(z, n1, p1, n2, p2){\n  prob <- 0\n  z_n <- -z #negative value\n\n  for (i in z_n:z){     #sum for all integer differences between observed value and its negative, inclusive\n    prob <- prob + diffBin(i, n1, p1, n2, p2)\n    }\n\n  return(prob)\n}\n```\n:::\n\nNow, a similar computation as above, but for 'this big or smaller in magnitude':\n\n::: {.cell}\n\n```{.r .cell-code}\n  (\n    mag_db_0 <- ltmag_diffBin(z, n1, p1, n2, p2)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4908031\n```\n:::\n:::\n\nThis implies there is a 49.1% chance of getting a difference *no larger than this one in magnitude* of +/-2 incidences between the treatments if the true incidence rates were equal.\n\n\\\n\n**And finally, what we were looking for:** the chance of 'a difference this small or smaller' as a function of the **true difference...**\n\nSet up an arbitrary vector of 'true differences' (to keep it simple, only change it in one direction for now ...)\n\n\nBelow, I plot\n\nY-axis: ’how likely would a difference in donations ‘as small or smaller in magnitude’” than we see in the data  against\n\nX-axis: if the “true difference in incidence rates” were of these magnitudes\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(scipen=999)\n\nB <- c(1, 1.5, 2, 2.5, 3, 4, 10)\n\np1 <- rep((d1+d2)/(n1+n2), length(B))\np2 <- p1*B\n\n\nas.list(ltmag_diffBin(z, n1, p1, n2, p2)*100) %>% format(digits=3, scientific=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"49.1\"             \"39.4\"             \"20.6\"             \"8.02\"            \n[5] \"2.51\"             \"0.153\"            \"0.00000000000855\"\n```\n:::\n\n```{.r .cell-code}\nprobmag <- ltmag_diffBin(z, n1, p1, n2, p2)\n\n\n#qplot(B, probmag, log  = \"x\", xlab = \"True relative incidence\", ylab =\"Prob. of difference this small\")\n\n(\n  probmag_plot <-\n    ggplot() +\n  aes(x=B, y=probmag) +\n  geom_point() +\n  scale_x_continuous(trans='log2') +\n    ylim(0,.51) +\n    xlab(\"True relative incidence rate\") +\n    ylab(\"Prob. diff. as small as obsd\")\n\n)\n```\n\n::: {.cell-output-display}\n![](binary_trial_computations_redacted_ed_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n\nHard-coded takeaways 15 Dec 2021 :\n\nOur data is consistent with ‘no difference’ (of course) ... but its also consistent with ‘a fairly large difference in incidence’\n\nE.g., even if one treatment truly lead to ‘twice as many donations as the other’, we still have a 20% chance of seeing a differences as small as the one we see (of 8 versus 6)\n\nWe can reasonably ‘rule out’ differences of maybe 2.5x or greater\n\n\nMain point: given the rareness of donations in this context, our sample size doesn’t let us make very strong conclusions in either directions … at least not yet. I hope that combined with other evidence, we will be able to infer more\n\n\n\n<!--\n## DR discussion of this case ... maybe obsolete\n\nWe get a 0.59% and a 0.50% conversion rate (share of emails who made at least one contribution in response) for control and treatment, respectively.\n\nHow likely would it be to have a 'difference in incidence this small or smaller' (either 0.09 pp or 0.09/0.5=0.18 proportional difference)...\n\nif the true differences in incidence were XXX or larger? (For now, assuming the actual incidence rate is 0.50 for the smaller-incidence treatment ... later we could have each of these follow a distribution.)\n\nHow?\n\nFor `num_sim` number of simulations - 'Control': $i=1..N$ draws from a binomial(0.005) - 'Treatment' N draws from a binomial(0.005\\*B) where B is the 'considered effect size' - Compute the `effect_i(B)` (the difference in share positive size ggof the simulated difference' for this simulation) - Compute: 'what share of simulations have a difference smaller in magnitude than the empirical one. I.e., \\$\\sum\\_i(\\|ES_i(B)\\| \\< \\|ES\\|) \\times \\frac{1}{N} \\$\n\nDo this for a range of considered effect sizes, e.g., $B \\in \\{0.5, 0.75, 1, 1.5, 2, 3, 4\\}$\n\n-->\n\n",
    "supporting": [
      "binary_trial_computations_redacted_ed_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": [],
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}