# Experiments: Qualitative and implementation design issues {#expt-qual-imp}

- See [Reinstein notes on 'why run an experiment'](https://daaronr.github.io/metrics_discussion/why-experiment-design.html#why-run-an-experiment-or-study) (somewhat more relevant to 'lab experiments')

- See informal 'practitioners' discussion [below](#eamt-qual), from 'EA market testing'

```{block2,  type='note'}

Note that much 'experiment and trial' relevant content is covered in the [surveys](#surveys) section. We will put in placeholders and cross-link.

```


## Proposed structure of section

- Basic design choices and terminology

- Types of experiments: 'lab and field'

- Formulating hypotheses and 'learning and adaptation goals'

- Hypothesis testing versus 'reinforcement learning' goals

- Design concerns and pitfalls

  - Confounded designs

  - Attrition and failed randomization

  - 'Demand effects'

  - Naturalness versus cleanliness

- Practical and implementation issues

    - Survey and experiment platforms (see '[surveys](#surveys)') chapter

    - Field experiments, A/B and lift tests, and marketing trials

    - Designing, coding, and implementing experiments: IT issues

    - Failure and success modes

    - Capturing outcome data

    - Pre-registration and pre-analysis plans

    - ... See Reinstein discussion notes on the benefits and costs [here](https://daaronr.github.io/metrics_discussion/quant-design-power.html#the-benefits-and-costs-of-pre-registration-a-typical-discussion)

# Design: quantitative issues {#expt-quant}

```{block2,  type='note'}

Note that much 'experiment and trial' relevant content is covered in the [surveys](#surveys) section. We will put in placeholders and cross-link.

```

## 'Treatment' assignment (blocking, randomization, etc)


### Adaptive, sequential and dynamic designs

- [Reinstein notes and links here](https://daaronr.github.io/metrics_discussion/quant-design-power.html#quant_design_power)

- Elsey: http://www.sequentialtesting.com/


## Planning, diagnosing and adjusting a design

### Specifying models, hypotheses, and statistical testing and inference approaches

(Just a brief here, this will be covered in more detail in the sections on statistical inference, testing, and analysis

## Power analyses (and other 'diagnosands')

<div class="marginnote">
Note: this will very much overlap the discussion of power analysis for *surveys*. Perhaps we put the simpler introduction there, and the more involved details here?
</div>


### Key resources and explainers

('Curate link' tools we found useful)

[Reinstein notes and code](https://daaronr.github.io/metrics_discussion/power.html)



### See ['Rethink_Priorities_Power_analysis_framework_2' in  appendix](#power-workflow)

This is a proposal and tools for a 'path to do' power testing (by Jamie Elsey; David Reinstein will weigh in too). I think this first focuses on a frequentist approach, but it's likely to also introduce a Bayesian approach.

```{block2,  type='note'}

DR: I'm putting it into an appendix to the bookdown for now. We may incorporate much of that into the present section.

An alternative to an 'appendix' is a standalone page which we can link here. This can sometimes be helpful; it allows a different format, may save time on knitting, may allow that other page to be better integrated elsewhere.

But for now, I'll make it a bookdown appendix, to help get us all used to the current format and avoid disagregation.

```
