# Experiments: Qualitative design, implementation {#expt-qual-imp}

- See [Reinstein notes on 'why run an experiment'](https://daaronr.github.io/metrics_discussion/why-experiment-design.html#why-run-an-experiment-or-study) (somewhat more relevant to 'lab experiments')

- See informal 'practitioners' discussion [below](#eamt-qual), from 'EA market testing'

::: {.alert .alert-secondary}


Note that much 'experiment and trial' relevant content is covered in the [surveys](#surveys) section. We will put in placeholders and cross-link.

:::


## Proposed structure of section

- Basic design choices and terminology

- Types of experiments: 'lab and field'

- Formulating hypotheses and 'learning and adaptation goals'

- Hypothesis testing versus 'reinforcement learning' goals

- Design concerns and pitfalls

  - Confounded designs

  - Attrition and failed randomization

  - 'Demand effects'

  - Naturalness versus cleanliness

- Practical and implementation issues

    - Survey and experiment platforms (see '[surveys](#surveys)') chapter

    - Field experiments, A/B and lift tests, and marketing trials

    - Designing, coding, and implementing experiments: IT issues

    - Failure and success modes

    - Capturing outcome data

    - Pre-registration and pre-analysis plans

    - ... See Reinstein discussion notes on the benefits and costs [here](https://daaronr.github.io/metrics_discussion/quant-design-power.html#the-benefits-and-costs-of-pre-registration-a-typical-discussion)

